configuration:
  projectName: insurance-eureka

eureka:
  server:
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: ${PORT:8070}

logging:
  level:
    com.netflix.eureka.registry: WARN

management:
  security:
    enabled: false

---
spring:
  profiles: local
eureka:
  instance:
    hostname: localhost
---
spring:
  profiles: aws
eureka:
  instance:
    hostname: lab-insurance-eureka.eu-west-1.elasticbeanstalk.com
---
spring:
  profiles: google-cloud
eureka:
  instance:
    hostname: localhost
