configuration:
  projectName: insurance-common

eureka:
  registerWithEureka: true
  fetchRegistry: true

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: *  

logging:
  level.org: INFO
  level.org.lab.insurance: DEBUG

---
spring:
  profiles: local
  data:
    mongodb:
      uri: mongodb://localhost/lab-insurance
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
---
spring:
  profiles: aws
eureka:
  client:
    serviceUrl:
      defaultZone: http://lab-insurance-eureka.eu-west-1.elasticbeanstalk.com/eureka/