#TODO pasar a cloud config

configuration:
  projectName: insurance-zuul

spring:
  application:
    name: insurance-zuul
  thymeleaf:
    #no cache templates under development phase
    cache: false
    
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

management:
  security:
    enabled: false

logging:
  level.org: DEBUG

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      #defaultZone: http://localhost:8070/eureka/
      defaultZone: http://lab-insurance-eureka.eu-west-1.elasticbeanstalk.com/eureka/

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    #TODO cambiar por los valores de eureka, aunque esta provocando un error
    #insurance-contract-common-gateway: /contracts/**
    #insurance-contract-common-gateway:
    #  path: /contracts/**
    #  url: http://localhost:8090/
    #legal-entities:
    #  path: /legal-entities/**
    #  url: http://localhost:8091/
    #portfolios:
    #  path: /portfolios/**
    #  url: http://localhost:8092/
    #assets:
    #  path: /assets/**
    #  url: http://localhost:8093/
    #orders:
    #  path: /orders/**
    #  url: http://localhost:8094/
    #accounting:
    #  path: /accounting/**
    #  url: http://localhost:8095/
    #contract-creation:
    #  path: /contract-creation/**
    #  url: http://localhost:8096/
    agreements:
      path: /agreements/**
      #serviceId: insurance-agreement-gateway
      serviceId: INSURANCE-AGREEMENT-GATEWAY
      stripPrefix: true


#ribbon:
#  eureka:
#    enabled: true

#ribbon:
#  eureka:
#   enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000
