configuration:
  projectName: insurance-common

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lab-insurance

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

management:
  context-path: /admin
  security:
    enabled: false

logging:
  level.org.lab: DEBUG
