#TODO pasar a cloud config

configuration:
  projectName: insurance-zuul

spring:
  application:
    name: insurance-zuul
  thymeleaf:
    #no cache templates under development phase
    cache: false
    
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

management:
  security:
    enabled: false

logging:
  level.org: INFO

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://lab-insurance-eureka.eu-west-1.elasticbeanstalk.com}/eureka/

zuul:
  prefix: /api
  routes:
    agreements:
      path: /agreements/**
      serviceId: insurance-agreement-gateway
    #stripPrefix: true

    #TODO cambiar por los valores de eureka, aunque esta provocando un error
    #insurance-contract-common-gateway: /contracts/**
    #insurance-contract-common-gateway:
    #  path: /contracts/**
    #  url: http://localhost:8090/
    #legal-entities:
    #  path: /legal-entities/**
    #  url: http://localhost:8091/
    #portfolios:
    #  path: /portfolios/**
    #  url: http://localhost:8092/
    #assets:
    #  path: /assets/**
    #  url: http://localhost:8093/
    #orders:
    #  path: /orders/**
    #  url: http://localhost:8094/
    #accounting:
    #  path: /accounting/**
    #  url: http://localhost:8095/
    #contract-creation:
    #  path: /contract-creation/**
    #  url: http://localhost:8096/

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 20000

#ribbon:
#  eureka:
#    enabled: true
#    ReadTimeout: 20000
#    ConnectTimeout: 20000
