configuration:
  projectName: insurance-common

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lab-insurance

eureka:
  client:
    serviceUrl:
      #defaultZone: http://localhost:8070/eureka/
      defaultZone: http://lab-insurance-eureka.eu-west-1.elasticbeanstalk.com/eureka/

management:
#  context-path: /admin
  security:
    enabled: false

logging:
  level.org: INFO
