configuration:
  projectName: insurance-eureka

eureka:
  instance:
    hostname: localhost
  server:
    eviction-interval-timer-in-ms: 10000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
#TODO falta configuracion en elasticbeanstalk
#  port: ${PORT:8070}
  port: 8070 

logging:
  level:
    com.netflix.eureka.registry: WARN

---
spring:
  profiles: aws
server:
  port: 80